#+TITLE: Notes On [[https://kubernetes.io/docs/tutorials/kubernetes-basics/][kubernetes basics]]
#+AUTHOR: Zhao WenBin

* Cluster Structure

** What is kubernets cluster

Kubernetes is a production-grade, open-source platform that orchestrates the
placement (scheduling) and execution of application containers within and
across computer clusters.

** Master and nodes

Masters manage the cluster and the nodes are used to host the running applications

** Note

- Kubernetes cluster 中运行的是 containerized (容器化的) application，意味着应用不假设于 host 环境
- node 中运行有 kubelet 与 master 交互，并可以对本地的 docker 或 rkt 环境进行操作
** TODO cluster-interactive

google doc can not been seen
* Deploy an App

** Deployment Basic

A Deployment is responsible for creating and updating instances of your application

** Container Backend

Applications need to be packaged into one of the supported container formats in order to be deployed on Kubernetes.

** Note

- =kubectl= is a command line tools, which interactive with server use API. Just like beeline with hive
- After deployment, deployment controller is responsible for self-healing and recover from failure
- Kubernetes provides extra features such as *scale* and *update*

** TODO Interactive

Google doc can not been seen...

- ~kubectl run --image=... --port=...~ to make a new deployment
- ~kubectl get deployment~ to see the deployment
- Can also see running process with ~kubectl get pod~
- ~kubectl proxy~ to forward http request to inner-cluster network

* Explore Your App

** Pods

A Pod is a group of one or more application containers( such as Docker or rkt) and 
includes shared storage (volumes), IP Address and information about how to run them.

Containers in pod are relatively tightly coupled, they would be co-located and co-scheduled,
and have shared context.

The Pod will be act as a atomic unit and *always* run on a single Node.

** Nodes

*** best practice

Containers should only be scheduled together in a single Pod if they are tightly coupled and need to share resource such as disk.

*** note

- A Pod always runs on a Node. (for shared context maybe?)
- Multiple Pods can run on one Node.
- Every node runs at least a kubelet and a container runtime (like Docker, rkt)

* Useful commands

** version

** cluster-info
** get
*** nodes
*** pods
*** deployment
** run
** create
** TODO logs
** TODO exec
