* finalist

* affiliated

* compensation

** mean

Compensation is money that someone who has experienced loss or
suffering claims from the person or organization responsible, or from
the state.

* screen out

** mean

To remove sb. from a group that is being examined.

** sample

/Screening out job applicaants who have less than three years' experience./

* Caucasian

** pronounce

=[kɔˈkeʒn]= 

** mean

高加索人

* harassment

** pronounce

=[h'ræsmnt]=

** mean

Harassment is behaviour which is intended to trouble or annoy someone,
for example repeated attacks on them or attempts to cause them
problems.

** sample

Another survey found that 51 percent of women had experienced some
form of sexual harassment in their working lives.

* obligation

** mean

If you have an obligation to do something, it is your duty to do that thing

** sample

When teachers assign homework, students usually feel an obligation to
do it.

* morale

** pronounce

=[mˈræl]=

** mean

Morale is the amount of confidence and cheerfulness that a group of
people have.

** sample

Many pilots are suffering from low morale.

* retaliation

** mean

If you retaliate when someone harms or annoys you, you do something
which harms or annoys them in return.

