#+TITLE: NGINX 
#+AUTHOR: Zhao WenBin

* Reverse Proxy

** What is Proxy?

Proxying is typically used to distribute the load among several
servers, seamlessly show content from different websites, or pass
requests for processing to application servers over protocols other
than HTTP.

** Why reverse proxy?

1. Expose internal service
2. Traffic Balance
3. Security
4. Accelerate (buffering)

** Feature

- non-HTTP Protocol: FastCGI, uwsgi, SCGI, memcached
- buffering
- header modify

** Request-Response flow

When NGINX proxies a request, it sends the request to a specified
proxied server, fetches the response, and sends it back to the client.

** Configuration

*** Basic

Forward request with URL =/some/path/page.html= to =http://www.example.com/link/page.html=

#+BEGIN_SRC text
  location /some/path/ {
      proxy_pass http://www.example.com/link/;
  }
#+END_SRC

There are =**_pass= directive for non-HTTP protocol:
- =fastcfg_pass=
- =uwsgi_pass=
- =scgi_pass=
- =memcached_pass=

*** TODO Named Group

*** Header Modification

#+BEGIN_SRC text
  location /some/path/ {
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_pass http://localhost:8000;
  }
#+END_SRC

*** Buffer

- =proxy_buffering= :: default *on*
- =proxy_buffer_size= :: The first part of the response from a proxied server is stored in a separate buffer
- =proxy_buffer= :: =proxy_buffers 16 4k= specific the number of buffers and the size allocated for a request

#+BEGIN_SRC text
  location /some/path/ {
      proxy_buffers 16 4k;
      proxy_buffer_size 2k;
      proxy_pass http://localhost:8000;
  }
#+END_SRC

*** Choosing an Outgoing IP Address

- For multiple network interface
- Specify the =proxy_bind= directive and the IP address of the necessary network interface

#+BEGIN_SRC text
  location /app1/ {
      proxy_bind 127.0.0.1;
      proxy_pass http://example.com/app1/;
  }

  location /app2/ {
      proxy_bind 127.0.0.2;
      proxy_pass http://example.com/app2/;
  }
#+END_SRC
** Note
*** TODO What does "Reverse" mean?
*** TODO vs _Iptables_
*** TODO Balancer
