* Digest

- Choosing for myself turned out to be much more valuable in the long
  run than simply accepting or rejecting a single point of view.

- How will a nation survive if teaching children about money continues
  to be left to parents -- most of whom will be, or already are, poor?

- People really do shape their lives through their thoughts.

- Broke is temporary. Poor is eternal.

- "I don't work for money!" were words he repeat over and over. "Money
  works for me"

- He stopped once he realized that I knew and fully understood what he
  had been trying to drum into my often-thick skull.

- The lessons are meant not to be answers, but _guideposts_ that will
  assist you and your children to grow wealthier _no matter what
  happens_ in world of increasing change and uncertainty.

* Words

- charismatic

- tremendous :: Although both men had tremendous respect for education and learning, they disagreed about what they thought was important to learn.

- intrigued :: The contract in their points of view, particularly
               about money, was so extreme that I grew curious and
               intrigued.

- scholastic

- substantial

- forbade :: forbid

- fanatical

- perks :: He was always concerned about pay raises, retirement,
           plans, medical benefits, sick leave, vacation days, and
           other perks.

- retirement-and-entitlement :: He was impressed with two of his
     uncles who joined the military and earned a
     retirement-and-entitlement package for life after twenty years of
     active service.

- PX privileges

- tenure

- entitle :: I've worked hard for the government, and I'm entitled to
             these benefits.

- emphatic :: He was emphatic about being financially competent.

- prophecy

- flat broke :: Even when he was flat broke after a major financial
                setback, he continued to refer to himself as a rich
                man




* Note

** afford of money

One lets you off the hook, and the other forces you to think.

*** risk

- When it comes to money, play it safe. Don't take risks

- Learn to manage risk.

- I can't afford it
- How can I afford it

** mental laziness

- Exercise our brains

- Proper physical exercise increases your chances for health, and
  proper mental exercise increases your chances for wealth.

** attitude to the tax

- The rich should pay more in taxes to take care of those less fortunate
- Taxes punish those who produce and reward those who don't produce

** attitude to study

- study hard so you can find a good company to work for
- study hard so you can find a good company to buy

** attitude to job

- how to write an impressive resume so I could find a good job
- how to write strong business and financial plans so I could create jobs.


* Poem

** The Road Not Taken

by Robert Frost

#+BEGIN_VERSE
Two roads diverged in a yellow wood,
And sorry I could not travel both
And be one traveler, long I stood
And looked down one as far as I could
To where it bent in the undergrowth;
Then took the other, as just as fair,
And having perhaps the better claim,
Because it was grassy and wanted wear
Though as for that the passing there
Had worn them really about the same,
And both that morning equally lay
In leaves no step had trodden black.
Oh, I kept the first for another day!
Yet knowing how way leads onto way,
I doubted if I should ever come back.
I shall be telling this with a sigh
Somewhere ages and ages hence;
Two roads diverged in a wood, and I--
I took the one less traveled by,
And that has made all the difference.
And that has made all the difference.
#+END_VERSE
